### ISSUE TITLE
Bug in compute_posterior() function, expects enumerate_IPs_RG()

### ISSUE THREAD

**Issue by shaziaruybal** [aimeertaylor/Pv3Rs#2]
Hi @aimeertaylor, have been playing around with Pv3Rs but found a potential bug in the `compute_posterior()` function that I wanted to flag. This may be due to some of the renaming changes, potentially around the time of commit 148a36205c3e6d413587828a280e5718da55ca32? The error arises when `compute_posterior()` sources `RG_inference()` see below, https://github.com/aimeertaylor/Pv3Rs/blob/b5ededb26e68857c24fdc94f476da9de29cddd33/R/compute_posterior.R#L360
which then expects the `enumerate_IPs_RG` function, see below, 
https://github.com/aimeertaylor/Pv3Rs/blob/d5ab90f8aceb6c0ed8f60f86864bed5413fb44fd/R/RG_inference.R#L94

If I include the [`enumerate_IPs_RG()`](https://github.com/aimeertaylor/Pv3Rs/blob/main/R/enumerate_IPs_RG.R)  function in my `.GlobalEnv` it runs fine - however I am not sure if this fix is valid for current implementation due to the active development of the package. 

A reproducible example below (using the example within the function documentation), when installing via GitHub:

```
devtools::install_github("aimeertaylor/Pv3Rs")
library(Pv3Rs)

# ===========================================================================
# Example where alleles are named arbitrarily
# ===========================================================================
# Data on an enrolment episode and a recurrence:
y <- list(episode0 = list(marker1 = c("Tinky Winky", "Dipsy"),
                          marker2 = c("Laa-Laa", "Po")),
          episode1 = list(marker1 = "Tinky Winky",
                          marker2 = "Laa-Laa"))

# Allele frequencies:
fs <- list(
  marker1 = setNames(c(0.4, 0.6), c("Tinky Winky", "Dipsy")),
  marker2 = setNames(c(0.2, 0.8), c("Laa-Laa", "Po"))
)

# Compute posterior probabilities using default uniform prior, note that
# since there is only one recurrence, the marginal probabilities are the same
# as the joint probabilities:
compute_posterior(y, fs)
```

The error message is: 
`Number of valid graphs is 9
=========================================================================================================|
Computing log p(Y|RG) for 9 RGs
Error in enumerate_IPs_RG(RG) : 
  could not find function "enumerate_IPs_RG"`

A fix would potentially require renaming the below to updated function naming conventions https://github.com/aimeertaylor/Pv3Rs/blob/d5ab90f8aceb6c0ed8f60f86864bed5413fb44fd/R/RG_inference.R#L94

or updating the [NAMESPACE](https://github.com/aimeertaylor/Pv3Rs/blob/main/NAMESPACE) to include `enumerate_IPs_RG`. 

Many thanks for your help with this!

**Comment by aimeertaylor** [comment]
Hi Shazia, thanks for raising this. I'm on it now. I'll let you know when its fixed

**Comment by aimeertaylor** [comment]
Bug fixed thanks to Yong See.
